# Generated by Django 5.2.18 on 2026-10-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_recruitment", "0004_vettingreport_corp_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordIntelChannel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label for this channel (e.g. 'Imperium Blacklist', 'Public Intel')",
                        max_length=100,
                    ),
                ),
                (
                    "guild_id",
                    models.CharField(blank=True, default="", help_text="Discord Server / Guild ID", max_length=64),
                ),
                (
                    "guild_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Discord Server Name for reference (e.g. 'The Initiative Public')",
                        max_length=100,
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(help_text="Discord Channel Snowflake ID to fetch messages from", max_length=64),
                ),
                (
                    "user_token",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Discord user token override for this specific channel. If blank, uses global token from config.",
                        max_length=255,
                    ),
                ),
                (
                    "sync_interval_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Sync interval in minutes (e.g. 15, 30, 60, 360, 1440)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether background synchronization and vetting scanning is active for this channel",
                    ),
                ),
                (
                    "default_severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="high",
                        help_text="Risk severity flagged when an applicant's name is mentioned in this channel",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_id", models.CharField(blank=True, default="", max_length=64)),
                ("total_messages_stored", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Discord Intel Channel",
                "verbose_name_plural": "Discord Intel Channels",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="recruitmentconfig",
            name="discord_user_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Default Discord User Token to access and synchronize configured intel channels.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="DiscordIntelMessage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("discord_message_id", models.CharField(db_index=True, max_length=64)),
                ("author_id", models.CharField(blank=True, default="", max_length=64)),
                ("author_name", models.CharField(blank=True, default="", max_length=128)),
                ("content", models.TextField()),
                ("sent_at", models.DateTimeField(db_index=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="aa_recruitment.discordintelchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Intel Message",
                "verbose_name_plural": "Discord Intel Messages",
                "ordering": ["-sent_at"],
                "unique_together": {("channel", "discord_message_id")},
            },
        ),
    ]
