# Generated by Django 5.2.18 on 2026-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aa_recruitment", "0005_discordintelchannel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorpActivitySnapshot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("corporation_id", models.BigIntegerField(db_index=True)),
                ("corporation_name", models.CharField(max_length=150)),
                ("snapshot_date", models.DateField(db_index=True)),
                ("active_count", models.PositiveIntegerField(default=0)),
                ("low_count", models.PositiveIntegerField(default=0)),
                ("inactive_count", models.PositiveIntegerField(default=0)),
                ("dormant_count", models.PositiveIntegerField(default=0)),
                ("total_members", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Corp Activity Snapshot",
                "verbose_name_plural": "Corp Activity Snapshots",
                "ordering": ["snapshot_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CorpCombatStats",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("corporation_id", models.BigIntegerField(db_index=True, unique=True)),
                ("corporation_name", models.CharField(max_length=150)),
                ("corporation_ticker", models.CharField(blank=True, default="", max_length=10)),
                ("alliance_id", models.BigIntegerField(blank=True, null=True)),
                ("alliance_name", models.CharField(blank=True, default="", max_length=150)),
                ("member_count", models.PositiveIntegerField(default=0)),
                (
                    "is_auth_corp",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this corporation is an active internal member corporation in Alliance Auth",
                    ),
                ),
                ("ships_destroyed", models.PositiveIntegerField(default=0)),
                ("ships_lost", models.PositiveIntegerField(default=0)),
                ("isk_destroyed", models.BigIntegerField(default=0)),
                ("isk_lost", models.BigIntegerField(default=0)),
                (
                    "months_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured monthly breakdown: kills, losses, isk destroyed, and isk lost per YYYYMM",
                    ),
                ),
                ("raw_stats", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Corp Combat Stats",
                "verbose_name_plural": "Corp Combat Stats",
                "ordering": ["corporation_name"],
            },
        ),
        migrations.CreateModel(
            name="CorpMemberActivity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("corporation_id", models.BigIntegerField(db_index=True)),
                ("character_id", models.BigIntegerField(db_index=True)),
                ("character_name", models.CharField(db_index=True, max_length=150)),
                ("main_character_name", models.CharField(blank=True, default="", max_length=150)),
                ("is_main", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("low", "Low"),
                            ("inactive", "Inactive"),
                            ("dormant", "Dormant"),
                        ],
                        db_index=True,
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("kills_30d", models.PositiveIntegerField(default=0)),
                ("losses_30d", models.PositiveIntegerField(default=0)),
                ("isk_destroyed_30d", models.BigIntegerField(default=0)),
                ("isk_lost_30d", models.BigIntegerField(default=0)),
                ("kills_90d", models.PositiveIntegerField(default=0)),
                ("losses_90d", models.PositiveIntegerField(default=0)),
                ("isk_destroyed_90d", models.BigIntegerField(default=0)),
                ("isk_lost_90d", models.BigIntegerField(default=0)),
                ("last_activity_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Corp Member Activity",
                "verbose_name_plural": "Corp Member Activities",
                "ordering": ["-kills_30d", "character_name"],
                "unique_together": {("corporation_id", "character_id")},
            },
        ),
    ]
