# Generated by Django 5.2.18 on 2026-10-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aa_recruitment", "0006_corpactivitysnapshot_corpcombatstats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpmemberactivity",
            name="isk_destroyed_120d",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="corpmemberactivity",
            name="isk_destroyed_alltime",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="corpmemberactivity",
            name="isk_lost_120d",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="corpmemberactivity",
            name="isk_lost_alltime",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="corpmemberactivity",
            name="kills_120d",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="corpmemberactivity",
            name="kills_alltime",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="corpmemberactivity",
            name="losses_120d",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="corpmemberactivity",
            name="losses_alltime",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
